# --- SERVER CONFIG ---
server.port=${PORT:8080}

# --- DATABASE CONFIG ---
# Cú pháp: ${TEN_BIEN_TREN_RENDER : gia_tri_mac_dinh_chay_local}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:54322/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- SUPABASE AUTH ---
supabase.url=${SUPABASE_URL:http://127.0.0.1:54321}
supabase.key=${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU} 

jwt.secret=${SUPABASE_JWT_SECRET:super-secret-jwt-token-with-at-least-32-characters-long}



