-- V1: Initial database schema for SLIB

-- ========================================
-- Custom Types
-- ========================================
DO $$ BEGIN
    CREATE TYPE seat_status AS ENUM ('AVAILABLE', 'UNAVAILABLE', 'BOOKED', 'HOLDING');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('STUDENT', 'LIBRARIAN', 'ADMIN');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- ========================================
-- Helper Functions
-- ========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION is_staff()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN TRUE; -- Placeholder, implement actual staff check
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_current_user_id()
RETURNS UUID AS $$
BEGIN
    RETURN NULL; -- Placeholder, implement actual user ID retrieval
END;
$$ LANGUAGE plpgsql;

-- ========================================
-- Users Table (must be created first - many FKs reference this)
-- ========================================
CREATE TABLE IF NOT EXISTS users (
    id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid (),
    student_code VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    role user_role NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    reputation_score INTEGER DEFAULT 100,
    noti_device VARCHAR(255),
    created_at TIMESTAMP(6) DEFAULT NOW(),
    updated_at TIMESTAMP(6) DEFAULT NOW()
);

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================
-- Areas Table
-- ========================================
CREATE TABLE IF NOT EXISTS areas (
    area_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_name VARCHAR(255) NOT NULL UNIQUE,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    position_x INTEGER,
    position_y INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    locked BOOLEAN NOT NULL DEFAULT FALSE
);

-- ========================================
-- Area Factories Table
-- ========================================
CREATE TABLE IF NOT EXISTS area_factories (
    factory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factory_name VARCHAR(255) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    position_x INTEGER NOT NULL,
    position_y INTEGER NOT NULL,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    area_id BIGINT NOT NULL REFERENCES areas (area_id)
);

-- ========================================
-- Categories Table
-- ========================================
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    color_code VARCHAR(20),
    created_at TIMESTAMP(6) DEFAULT NOW()
);

-- ========================================
-- News Table
-- ========================================
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    summary TEXT,
    content TEXT NOT NULL,
    image_url TEXT,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    view_count INTEGER NOT NULL DEFAULT 0,
    published_at TIMESTAMP(6),
    created_at TIMESTAMP(6) DEFAULT NOW(),
    updated_at TIMESTAMP(6) DEFAULT NOW(),
    user_id UUID REFERENCES users (id),
    category_id BIGINT REFERENCES categories (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_news_published ON news (
    is_published,
    published_at DESC
);

CREATE TRIGGER update_news_updated_at
    BEFORE UPDATE ON news
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================
-- Zones Table
-- ========================================
CREATE TABLE IF NOT EXISTS zones (
    zone_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_name VARCHAR(255) NOT NULL,
    zone_des VARCHAR(255),
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    position_x INTEGER NOT NULL,
    position_y INTEGER NOT NULL,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    area_id BIGINT NOT NULL REFERENCES areas (area_id)
);

-- ========================================
-- Zone Amenities Table
-- ========================================
CREATE TABLE IF NOT EXISTS zone_amenities (
    amenity_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amenity_name VARCHAR(100) NOT NULL,
    zone_id INTEGER NOT NULL REFERENCES zones (zone_id)
);

-- ========================================
-- Seats Table
-- ========================================
CREATE TABLE IF NOT EXISTS seats (
    seat_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_code VARCHAR(255) NOT NULL,
    seat_status seat_status NOT NULL DEFAULT 'AVAILABLE',
    row_number INTEGER NOT NULL,
    column_number INTEGER NOT NULL,
    zone_id INTEGER NOT NULL REFERENCES zones (zone_id),
    hold_expires_at TIMESTAMP,
    held_by_user UUID REFERENCES users (id)
);

-- ========================================
-- Reservations Table
-- ========================================
CREATE TABLE IF NOT EXISTS reservations (
    reservation_id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id UUID NOT NULL REFERENCES users (id),
    seat_id INTEGER NOT NULL REFERENCES seats (seat_id),
    start_time TIMESTAMP(6) NOT NULL,
    end_time TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    created_time TIMESTAMP(6) DEFAULT NOW(),
    created_at TIMESTAMP(6) DEFAULT NOW()
);

-- ========================================
-- Access Logs Table
-- ========================================
CREATE TABLE IF NOT EXISTS access_logs (
    log_id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id UUID REFERENCES users (id),
    device_id VARCHAR(50) NOT NULL,
    check_in_time TIMESTAMP(6) NOT NULL,
    check_out_time TIMESTAMP(6),
    reservation_id UUID REFERENCES reservations (reservation_id)
);

-- ========================================
-- User Settings Table
-- ========================================
CREATE TABLE IF NOT EXISTS user_settings (
    user_id UUID NOT NULL PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    language_code VARCHAR(10) DEFAULT 'vi',
    theme_mode VARCHAR(20) DEFAULT 'light',
    is_booking_remind_enabled BOOLEAN DEFAULT TRUE,
    is_ai_recommend_enabled BOOLEAN DEFAULT TRUE,
    is_hce_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) DEFAULT NOW(),
    updated_at TIMESTAMP(6) DEFAULT NOW()
);

CREATE TRIGGER update_user_settings_updated_at
    BEFORE UPDATE ON user_settings
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================
-- Refresh Tokens Table
-- ========================================
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id UUID NOT NULL REFERENCES users (id),
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    device_info VARCHAR(255),
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW()
);

-- ========================================
-- Chat Logs Table
-- ========================================
CREATE TABLE IF NOT EXISTS chat_logs (
    message_id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id UUID NOT NULL REFERENCES users (id),
    sender VARCHAR(255) NOT NULL,
    message_content TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT NOW()
);

-- ========================================
-- Feedbacks Table
-- ========================================
CREATE TABLE IF NOT EXISTS feedbacks (
    feedback_id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users (id),
    content TEXT NOT NULL,
    sentiment_score NUMERIC DEFAULT 0 NOT NULL,
    category VARCHAR(255) NOT NULL,
    status VARCHAR(255) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ========================================
-- Notifications Table
-- ========================================
CREATE TABLE IF NOT EXISTS notifications (
    notification_id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id UUID NOT NULL REFERENCES users (id),
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(255) NOT NULL,
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ========================================
-- Reputation History Table
-- ========================================
CREATE TABLE IF NOT EXISTS reputation_history (
    history_id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users (id),
    change_amount INTEGER NOT NULL,
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ========================================
-- Student Schedules Table
-- ========================================
CREATE TABLE IF NOT EXISTS student_schedules (
    schedule_id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users (id),
    day_of_week INTEGER NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL
);

-- ========================================
-- Library Settings Table
-- ========================================
CREATE TABLE IF NOT EXISTS library_settings (
    id INTEGER NOT NULL PRIMARY KEY,
    open_time VARCHAR(255) NOT NULL DEFAULT '07:00',
    close_time VARCHAR(255) NOT NULL DEFAULT '21:00',
    working_days VARCHAR(255) NOT NULL DEFAULT '1,2,3,4,5,6',
    slot_duration INTEGER NOT NULL DEFAULT 60,
    max_booking_days INTEGER NOT NULL DEFAULT 7,
    max_bookings_per_day INTEGER NOT NULL DEFAULT 3,
    max_hours_per_day INTEGER NOT NULL DEFAULT 4
);

-- Insert default library settings
INSERT INTO
    library_settings (
        id,
        open_time,
        close_time,
        working_days,
        slot_duration,
        max_booking_days,
        max_bookings_per_day,
        max_hours_per_day
    )
VALUES (
        1,
        '07:00',
        '21:00',
        '1,2,3,4,5,6',
        60,
        7,
        3,
        4
    )
ON CONFLICT (id) DO NOTHING;