-- ============================================================
-- V31: Create missing entity tables and add missing columns
--
-- Audit found these JPA entities have no corresponding
-- CREATE TABLE in any Flyway migration:
--   1. ai_config
--   2. ai_knowledge_stores
--   3. ai_materials
--   4. ai_material_items
--   5. chat_sessions (AI chat)
--   6. chat_messages (AI chat)
--   7. knowledge_base
--   8. prompt_templates
--   9. student_behaviors
--  10. otp_tokens
--
-- Missing columns in existing tables:
--   - seats.nfc_tag_uid
-- ============================================================

-- ========================================
-- 1. AI Config Table
-- ========================================
CREATE TABLE IF NOT EXISTS ai_config (
    id SERIAL PRIMARY KEY,
    config_key VARCHAR(100) UNIQUE NOT NULL,
    config_value TEXT NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

DROP TRIGGER IF EXISTS update_ai_config_updated_at ON ai_config;
CREATE TRIGGER update_ai_config_updated_at
    BEFORE UPDATE ON ai_config
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================
-- 2. AI Knowledge Stores Table
-- ========================================
CREATE TABLE IF NOT EXISTS ai_knowledge_stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    store_type VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    document_count INTEGER NOT NULL DEFAULT 0,
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

DROP TRIGGER IF EXISTS update_ai_knowledge_stores_updated_at ON ai_knowledge_stores;
CREATE TRIGGER update_ai_knowledge_stores_updated_at
    BEFORE UPDATE ON ai_knowledge_stores
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================
-- 3. AI Materials Table
-- ========================================
CREATE TABLE IF NOT EXISTS ai_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_store_id BIGINT NOT NULL REFERENCES ai_knowledge_stores (id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

DROP TRIGGER IF EXISTS update_ai_materials_updated_at ON ai_materials;
CREATE TRIGGER update_ai_materials_updated_at
    BEFORE UPDATE ON ai_materials
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================
-- 4. AI Material Items Table
-- ========================================
CREATE TABLE IF NOT EXISTS ai_material_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id BIGINT NOT NULL REFERENCES ai_materials (id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    content TEXT,
    file_name VARCHAR(255),
    file_path VARCHAR(500),
    file_size BIGINT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ========================================
-- 5. Knowledge Base Table
-- ========================================
CREATE TABLE IF NOT EXISTS knowledge_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category VARCHAR(50),
    priority INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

DROP TRIGGER IF EXISTS update_knowledge_base_updated_at ON knowledge_base;
CREATE TRIGGER update_knowledge_base_updated_at
    BEFORE UPDATE ON knowledge_base
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================
-- 6. Chat Sessions Table (AI Chat)
-- ========================================
CREATE TABLE IF NOT EXISTS chat_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
    user_id UUID NOT NULL REFERENCES users (id),
    title VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

DROP TRIGGER IF EXISTS update_chat_sessions_updated_at ON chat_sessions;
CREATE TRIGGER update_chat_sessions_updated_at
    BEFORE UPDATE ON chat_sessions
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_chat_sessions_user ON chat_sessions (user_id);

-- ========================================
-- 7. Chat Messages Table (AI Chat)
-- ========================================
CREATE TABLE IF NOT EXISTS chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
    session_id UUID NOT NULL REFERENCES chat_sessions (id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    tokens_used INTEGER,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages (session_id);

-- ========================================
-- 8. Prompt Templates Table
-- ========================================
CREATE TABLE IF NOT EXISTS prompt_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    prompt TEXT NOT NULL,
    context VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

DROP TRIGGER IF EXISTS update_prompt_templates_updated_at ON prompt_templates;
CREATE TRIGGER update_prompt_templates_updated_at
    BEFORE UPDATE ON prompt_templates
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================
-- 9. Student Behaviors Table (Analytics)
-- ========================================
CREATE TABLE IF NOT EXISTS student_behaviors (
    id SERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users (id),
    behavior_type VARCHAR(50) NOT NULL,
    description TEXT,
    related_booking_id UUID,
    related_seat_id INTEGER,
    related_zone_id INTEGER,
    points_impact INTEGER,
    metadata TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

DROP TRIGGER IF EXISTS update_student_behaviors_updated_at ON student_behaviors;
CREATE TRIGGER update_student_behaviors_updated_at
    BEFORE UPDATE ON student_behaviors
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_student_behaviors_user ON student_behaviors (user_id);

CREATE INDEX IF NOT EXISTS idx_student_behaviors_type ON student_behaviors (behavior_type);

-- ========================================
-- 10. OTP Tokens Table
-- ========================================
CREATE TABLE IF NOT EXISTS otp_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    type VARCHAR(30) NOT NULL DEFAULT 'PASSWORD_RESET',
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_otp_tokens_email ON otp_tokens (email);

-- ========================================
-- 11. Add missing column: seats.nfc_tag_uid
-- ========================================
ALTER TABLE seats
ADD COLUMN IF NOT EXISTS nfc_tag_uid VARCHAR(255) UNIQUE;