ALTER TABLE seats
    ADD COLUMN IF NOT EXISTS is_visible BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE seats
    ADD COLUMN IF NOT EXISTS retired_at TIMESTAMP NULL;

UPDATE seats
SET is_visible = TRUE
WHERE is_visible IS NULL;
