# --- SERVER CONFIG ---
server.port=8080

# --- DATABASE CONFIG (SUPABASE) ---
spring.datasource.url=jdbc:postgresql://db.twvifiysbagdcllxxzyz.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=1XyFoM3Bfymd5648

spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE CONFIG ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true