


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;




ALTER SCHEMA "public" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."seat_status" AS ENUM (
    'AVAILABLE',
    'UNAVAILABLE',
    'BOOKED'
);


ALTER TYPE "public"."seat_status" OWNER TO "postgres";


CREATE TYPE "public"."user_role" AS ENUM (
    'STUDENT',
    'LIBRARIAN',
    'ADMIN'
);


ALTER TYPE "public"."user_role" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."create_user_settings_automatically"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    INSERT INTO public.user_settings (user_id)
    VALUES (NEW.id)
    ON CONFLICT (user_id) DO NOTHING; 
    
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."create_user_settings_automatically"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_current_user_id"() RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  RETURN (SELECT id FROM public.users WHERE supabase_uid = auth.uid());
END;
$$;


ALTER FUNCTION "public"."get_current_user_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_staff"() RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.users 
    WHERE supabase_uid = auth.uid() 
    AND role IN ('ADMIN', 'LIBRARIAN')
  );
END;
$$;


ALTER FUNCTION "public"."is_staff"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."access_logs" (
    "log_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "reservation_id" "uuid",
    "check_in_time" timestamp without time zone DEFAULT "now"() NOT NULL,
    "check_out_time" timestamp without time zone,
    "device_id" character varying(50) NOT NULL
);


ALTER TABLE "public"."access_logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."area_factories" (
    "factory_id" bigint NOT NULL,
    "color" character varying(255),
    "factory_name" character varying(255) NOT NULL,
    "height" integer NOT NULL,
    "position_x" integer NOT NULL,
    "position_y" integer NOT NULL,
    "width" integer NOT NULL,
    "area_id" bigint NOT NULL
);


ALTER TABLE "public"."area_factories" OWNER TO "postgres";


ALTER TABLE "public"."area_factories" ALTER COLUMN "factory_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."area_factories_factory_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."areas" (
    "area_id" bigint NOT NULL,
    "area_name" character varying(255) NOT NULL,
    "height" integer NOT NULL,
    "is_active" boolean NOT NULL,
    "locked" boolean NOT NULL,
    "position_x" integer,
    "position_y" integer,
    "width" integer NOT NULL
);


ALTER TABLE "public"."areas" OWNER TO "postgres";


ALTER TABLE "public"."areas" ALTER COLUMN "area_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."areas_area_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "name" character varying(50) NOT NULL,
    "color_code" character varying(20) DEFAULT '#F37021'::character varying,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."categories_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."categories_id_seq" OWNED BY "public"."categories"."id";



CREATE TABLE IF NOT EXISTS "public"."chat_logs" (
    "message_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "sender" character varying(255) NOT NULL,
    "message_content" "text" NOT NULL,
    "timestamp" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."chat_logs" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."feedbacks" (
    "feedback_id" integer NOT NULL,
    "user_id" "uuid" NOT NULL,
    "content" "text" NOT NULL,
    "sentiment_score" numeric DEFAULT 0 NOT NULL,
    "category" character varying(255) NOT NULL,
    "status" character varying(255) DEFAULT 'PENDING'::character varying NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."feedbacks" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."feedbacks_feedback_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."feedbacks_feedback_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."feedbacks_feedback_id_seq" OWNED BY "public"."feedbacks"."feedback_id";



CREATE TABLE IF NOT EXISTS "public"."news" (
    "id" bigint NOT NULL,
    "title" character varying(255) NOT NULL,
    "summary" "text",
    "content" "text" NOT NULL,
    "image_url" character varying(255),
    "category_id" bigint,
    "author_id" bigint,
    "user_id" "uuid",
    "is_published" boolean DEFAULT false,
    "is_pinned" boolean DEFAULT false,
    "view_count" integer DEFAULT 0,
    "published_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."news" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."news_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."news_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."news_id_seq" OWNED BY "public"."news"."id";



CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "notification_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "title" character varying(255) NOT NULL,
    "message" "text" NOT NULL,
    "type" character varying(255) NOT NULL,
    "is_read" boolean DEFAULT false NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."reputation_history" (
    "history_id" integer NOT NULL,
    "user_id" "uuid" NOT NULL,
    "change_amount" integer NOT NULL,
    "reason" character varying(255) NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."reputation_history" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."reputation_history_history_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."reputation_history_history_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."reputation_history_history_id_seq" OWNED BY "public"."reputation_history"."history_id";



CREATE TABLE IF NOT EXISTS "public"."reservations" (
    "reservation_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "seat_id" integer NOT NULL,
    "start_time" timestamp without time zone NOT NULL,
    "end_time" timestamp without time zone NOT NULL,
    "status" character varying(255) NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "created_time" timestamp(6) without time zone
);


ALTER TABLE "public"."reservations" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."seats" (
    "seat_id" integer NOT NULL,
    "column_number" integer NOT NULL,
    "height" integer,
    "position_x" integer NOT NULL,
    "position_y" integer NOT NULL,
    "row_number" integer NOT NULL,
    "seat_code" character varying(255) NOT NULL,
    "seat_status" "public"."seat_status" NOT NULL,
    "width" integer,
    "zone_id" integer NOT NULL,
    CONSTRAINT "seats_seat_status_check" CHECK (("seat_status" = ANY (ARRAY['AVAILABLE'::"public"."seat_status", 'UNAVAILABLE'::"public"."seat_status", 'BOOKED'::"public"."seat_status"])))
);


ALTER TABLE "public"."seats" OWNER TO "postgres";


ALTER TABLE "public"."seats" ALTER COLUMN "seat_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."seats_seat_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."student_schedules" (
    "schedule_id" integer NOT NULL,
    "user_id" "uuid" NOT NULL,
    "day_of_week" integer NOT NULL,
    "start_time" time without time zone NOT NULL,
    "end_time" time without time zone NOT NULL
);


ALTER TABLE "public"."student_schedules" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."student_schedules_schedule_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."student_schedules_schedule_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."student_schedules_schedule_id_seq" OWNED BY "public"."student_schedules"."schedule_id";



CREATE TABLE IF NOT EXISTS "public"."user_settings" (
    "user_id" "uuid" NOT NULL,
    "is_hce_enabled" boolean DEFAULT false,
    "is_ai_recommend_enabled" boolean DEFAULT true,
    "is_booking_remind_enabled" boolean DEFAULT true,
    "theme_mode" character varying(20) DEFAULT 'light'::character varying,
    "language_code" character varying(10) DEFAULT 'vi'::character varying,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."user_settings" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "supabase_uid" "uuid",
    "student_code" character varying(20) NOT NULL,
    "full_name" character varying(255) NOT NULL,
    "email" character varying(255),
    "role" "public"."user_role" DEFAULT 'STUDENT'::"public"."user_role",
    "reputation_score" integer DEFAULT 100,
    "noti_device" character varying(255),
    "is_active" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "dob" "date"
);


ALTER TABLE "public"."users" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."zone_amenities" (
    "amenity_id" integer NOT NULL,
    "amenity_name" character varying(100) NOT NULL,
    "zone_id" integer NOT NULL
);


ALTER TABLE "public"."zone_amenities" OWNER TO "postgres";


ALTER TABLE "public"."zone_amenities" ALTER COLUMN "amenity_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."zone_amenities_amenity_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."zones" (
    "zone_id" integer NOT NULL,
    "zone_name" character varying(255) NOT NULL,
    "zone_des" character varying(255),
    "has_power_outlet" boolean DEFAULT false NOT NULL,
    "color" character varying(255),
    "height" integer NOT NULL,
    "is_locked" boolean NOT NULL,
    "position_x" integer NOT NULL,
    "position_y" integer NOT NULL,
    "width" integer NOT NULL,
    "area_id" bigint NOT NULL
);


ALTER TABLE "public"."zones" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."zones_zone_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."zones_zone_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."zones_zone_id_seq" OWNED BY "public"."zones"."zone_id";



ALTER TABLE ONLY "public"."categories" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."categories_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."feedbacks" ALTER COLUMN "feedback_id" SET DEFAULT "nextval"('"public"."feedbacks_feedback_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."news" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."news_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."reputation_history" ALTER COLUMN "history_id" SET DEFAULT "nextval"('"public"."reputation_history_history_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."student_schedules" ALTER COLUMN "schedule_id" SET DEFAULT "nextval"('"public"."student_schedules_schedule_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."zones" ALTER COLUMN "zone_id" SET DEFAULT "nextval"('"public"."zones_zone_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."access_logs"
    ADD CONSTRAINT "access_logs_pkey" PRIMARY KEY ("log_id");



ALTER TABLE ONLY "public"."area_factories"
    ADD CONSTRAINT "area_factories_pkey" PRIMARY KEY ("factory_id");



ALTER TABLE ONLY "public"."areas"
    ADD CONSTRAINT "areas_pkey" PRIMARY KEY ("area_id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."chat_logs"
    ADD CONSTRAINT "chat_logs_pkey" PRIMARY KEY ("message_id");



ALTER TABLE ONLY "public"."feedbacks"
    ADD CONSTRAINT "feedbacks_pkey" PRIMARY KEY ("feedback_id");



ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("notification_id");



ALTER TABLE ONLY "public"."reputation_history"
    ADD CONSTRAINT "reputation_history_pkey" PRIMARY KEY ("history_id");



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_pkey" PRIMARY KEY ("reservation_id");



ALTER TABLE ONLY "public"."seats"
    ADD CONSTRAINT "seats_pkey" PRIMARY KEY ("seat_id");



ALTER TABLE ONLY "public"."student_schedules"
    ADD CONSTRAINT "student_schedules_pkey" PRIMARY KEY ("schedule_id");



ALTER TABLE ONLY "public"."seats"
    ADD CONSTRAINT "uk8lmccdreqobms7sdg1u6ql70b" UNIQUE ("seat_code");



ALTER TABLE ONLY "public"."areas"
    ADD CONSTRAINT "uka6j1x82cbwl7iwvi1cygx3399" UNIQUE ("area_name");



ALTER TABLE ONLY "public"."user_settings"
    ADD CONSTRAINT "user_settings_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_student_code_key" UNIQUE ("student_code");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_supabase_uid_key" UNIQUE ("supabase_uid");



ALTER TABLE ONLY "public"."zone_amenities"
    ADD CONSTRAINT "zone_amenities_pkey" PRIMARY KEY ("amenity_id");



ALTER TABLE ONLY "public"."zones"
    ADD CONSTRAINT "zones_pkey" PRIMARY KEY ("zone_id");



CREATE INDEX "idx_news_published" ON "public"."news" USING "btree" ("is_published", "published_at" DESC);



CREATE OR REPLACE TRIGGER "on_user_created_insert_settings" AFTER INSERT ON "public"."users" FOR EACH ROW EXECUTE FUNCTION "public"."create_user_settings_automatically"();



CREATE OR REPLACE TRIGGER "update_news_updated_at" BEFORE UPDATE ON "public"."news" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_user_settings_updated_at" BEFORE UPDATE ON "public"."user_settings" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_users_updated_at" BEFORE UPDATE ON "public"."users" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."access_logs"
    ADD CONSTRAINT "access_logs_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("reservation_id");



ALTER TABLE ONLY "public"."access_logs"
    ADD CONSTRAINT "access_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."chat_logs"
    ADD CONSTRAINT "chat_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."feedbacks"
    ADD CONSTRAINT "feedbacks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "fk57amums6j9fkqwbpw4oceyw9i" FOREIGN KEY ("seat_id") REFERENCES "public"."seats"("seat_id");



ALTER TABLE ONLY "public"."seats"
    ADD CONSTRAINT "fk7h81rc4x559i472rmapi41e62" FOREIGN KEY ("zone_id") REFERENCES "public"."zones"("zone_id");



ALTER TABLE ONLY "public"."area_factories"
    ADD CONSTRAINT "fk965pdgwi9icijaxsvsvrl7f89" FOREIGN KEY ("area_id") REFERENCES "public"."areas"("area_id");



ALTER TABLE ONLY "public"."zone_amenities"
    ADD CONSTRAINT "fkdv0wr6plyqsoa0eux207psdso" FOREIGN KEY ("zone_id") REFERENCES "public"."zones"("zone_id");



ALTER TABLE ONLY "public"."zones"
    ADD CONSTRAINT "fkketu7oesje2dhfjl952rumg0m" FOREIGN KEY ("area_id") REFERENCES "public"."areas"("area_id");



ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."reputation_history"
    ADD CONSTRAINT "reputation_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."reservations"
    ADD CONSTRAINT "reservations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."student_schedules"
    ADD CONSTRAINT "student_schedules_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."user_settings"
    ADD CONSTRAINT "user_settings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_supabase_uid_fkey" FOREIGN KEY ("supabase_uid") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



CREATE POLICY "Public read categories" ON "public"."categories" FOR SELECT USING (true);



CREATE POLICY "Public read news" ON "public"."news" FOR SELECT USING (true);



CREATE POLICY "Public read zones" ON "public"."zones" FOR SELECT USING (true);



CREATE POLICY "Service Role Users" ON "public"."users" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Staff manage logs" ON "public"."access_logs" USING ("public"."is_staff"());



CREATE POLICY "Staff manage reputation" ON "public"."reputation_history" USING ("public"."is_staff"());



CREATE POLICY "Staff modify categories" ON "public"."categories" USING ("public"."is_staff"());



CREATE POLICY "Staff modify news" ON "public"."news" USING ("public"."is_staff"());



CREATE POLICY "Staff modify reservations" ON "public"."reservations" FOR UPDATE USING ("public"."is_staff"());



CREATE POLICY "Staff modify zones" ON "public"."zones" USING ("public"."is_staff"());



CREATE POLICY "Staff view all chat" ON "public"."chat_logs" FOR SELECT USING ("public"."is_staff"());



CREATE POLICY "Staff view all feedbacks" ON "public"."feedbacks" FOR SELECT USING ("public"."is_staff"());



CREATE POLICY "Staff view all reservations" ON "public"."reservations" FOR SELECT USING ("public"."is_staff"());



CREATE POLICY "User create reservations" ON "public"."reservations" FOR INSERT WITH CHECK (("user_id" = "public"."get_current_user_id"()));



CREATE POLICY "User manage own feedbacks" ON "public"."feedbacks" USING (("user_id" = "public"."get_current_user_id"()));



CREATE POLICY "User manage own schedule" ON "public"."student_schedules" USING (("user_id" = "public"."get_current_user_id"()));



CREATE POLICY "User send chat" ON "public"."chat_logs" FOR INSERT WITH CHECK (("user_id" = "public"."get_current_user_id"()));



CREATE POLICY "User view own chat" ON "public"."chat_logs" FOR SELECT USING (("user_id" = "public"."get_current_user_id"()));



CREATE POLICY "User view own logs" ON "public"."access_logs" FOR SELECT USING (("user_id" = "public"."get_current_user_id"()));



CREATE POLICY "User view own noti" ON "public"."notifications" FOR SELECT USING (("user_id" = "public"."get_current_user_id"()));



CREATE POLICY "User view own reputation" ON "public"."reputation_history" FOR SELECT USING (("user_id" = "public"."get_current_user_id"()));



CREATE POLICY "User view own reservations" ON "public"."reservations" FOR SELECT USING (("user_id" = "public"."get_current_user_id"()));



CREATE POLICY "Users can view own profile" ON "public"."users" FOR SELECT USING (("auth"."uid"() = "supabase_uid"));



ALTER TABLE "public"."access_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."chat_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feedbacks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."news" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."reputation_history" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."reservations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."student_schedules" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."zones" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT ALL ON SCHEMA "public" TO PUBLIC;

























































































































































GRANT ALL ON FUNCTION "public"."get_current_user_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_current_user_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_staff"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_staff"() TO "service_role";

















































