# --- SERVER CONFIG ---
server.port=${PORT:8081}

# --- DATABASE CONFIG (Đã fix - Dùng 4G) ---
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?stringtype=unspecified}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Slibdoancuoiki}
# spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?stringtype=unspecified
spring.datasource.username=postgres.hmsbwtukwbywmyvcqtby
spring.datasource.password=Slibdoancuoiki
spring.datasource.driver-class-name=org.postgresql.Driver


# --- Tối ưu kết nối (Tránh lỗi Max connection) ---
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# --- Hibernate Dev ---
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

# --- SUPABASE & JWT ---
supabase.url=${SUPABASE_URL:https://hmsbwtukwbywmyvcqtby.supabase.co}
supabase.key=${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtc2J3dHVrd2J5d215dmNxdGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5NDgxOTksImV4cCI6MjA4MTUyNDE5OX0.af4uQ1OiNg98uz5UxTNDho9_aSFhNf8LFiwtRbl3P10}

jwt.secret=${SUPABASE_JWT_SECRET:semi6pkLDE1X93p1vnY8BOZRofSBXT6rHOgKK2qJSc0kOPiO5NrUt26OXe9CXsGhos/TsAyhMa9+ul6uz2WIUA==}

# --- GATE SERVICE (HCE) ---
gate.secret={GATE_SECRET:SLIB_SECRET_GATE_FPT_123}

# --- CLOUDINARY ---
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dsupnjcqy}
cloudinary.api-key=${CLOUDINARY_API_KEY:356659581747979}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:HlvOnlX7oJNDnoGEmWm-Y6_EPlQ}

