# --- SERVER CONFIG ---
server.port=${PORT:8080}

# --- DATABASE CONFIG (Đã fix - Dùng 4G) ---
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?stringtype=unspecified}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Slibdoancuoiki}
# spring.datasource.driver-class-name=org.postgresql.Driver

# --- SUPABASE (Tạm tắt) ---
# spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?stringtype=unspecified
# spring.datasource.username=postgres.hmsbwtukwbywmyvcqtby
# spring.datasource.password=Slibdoancuoiki

# --- LOCAL DOCKER PostgreSQL (Pure) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/slib?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=Slib@123
spring.datasource.driver-class-name=org.postgresql.Driver


# --- Tối ưu kết nối (Tránh lỗi Max connection) ---
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# --- Hibernate Dev ---
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# --- JWT CONFIG (Local) ---
jwt.secret=${JWT_SECRET:SlibSecretKeyForJWTTokenGenerationMustBeAtLeast32BytesLong2024!}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000

# --- GOOGLE OAUTH ---
google.client-id=${GOOGLE_CLIENT_ID:262933313086-mhbevhu0b7hfqekchf6a99vnebjfr8b5.apps.googleusercontent.com}

# --- GATE SERVICE (HCE) ---
gate.secret={GATE_SECRET:SLIB_SECRET_GATE_FPT_123}

# --- CLOUDINARY ---
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:doyffqwu9}
cloudinary.api-key=${CLOUDINARY_API_KEY:521939253936156}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:KCjvVBJKSiI8tTd1LRrxVIrar-I}

# Cấu hình cho phép upload file tối đa 10MB (để không bị lỗi 413)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB