# --- SERVER CONFIG ---
server.port=${PORT:8081}

# --- DATABASE CONFIG ---
# QUAN TRỌNG: Dùng 127.0.0.1 thay vì localhost
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:54322/postgres}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.hmsbwtukwbywmyvcqtby}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Slibdoancuoiki}
spring.datasource.driver-class-name=org.postgresql.Driver

# QUAN TRỌNG: Dùng update để tự tạo bảng lần đầu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- SUPABASE AUTH ---
# supabase.url=${SUPABASE_URL:http://127.0.0.1:54321}
# # Key này dùng để gọi API Supabase (lấy từ Terminal ok)
# supabase.key=${SUPABASE_KEY:sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz} 

# # Secret này dùng để giải mã Token (Nên check lại bằng lệnh supabase status -o json)
# jwt.secret=${SUPABASE_JWT_SECRET:super-secret-jwt-token-with-at-least-32-characters-long}

supabase.url=${SUPABASE_URL:https://hmsbwtukwbywmyvcqtby.supabase.co}
# Key này dùng để gọi API Supabase (lấy từ Terminal ok)
supabase.key=${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtc2J3dHVrd2J5d215dmNxdGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5NDgxOTksImV4cCI6MjA4MTUyNDE5OX0.af4uQ1OiNg98uz5UxTNDho9_aSFhNf8LFiwtRbl3P10} 

# Secret này dùng để giải mã Token (Nên check lại bằng lệnh supabase status -o json)
jwt.secret=${SUPABASE_JWT_SECRET:semi6pkLDE1X93p1vnY8BOZRofSBXT6rHOgKK2qJSc0kOPiO5NrUt26OXe9CXsGhos/TsAyhMa9+ul6uz2WIUA==}