# --- SERVER CONFIG ---
server.port=${PORT:8081}

# --- DATABASE CONFIG (Đã fix - Dùng 4G) ---
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?stringtype=unspecified
spring.datasource.username=postgres.hmsbwtukwbywmyvcqtby
spring.datasource.password=Slibdoancuoiki
spring.datasource.driver-class-name=org.postgresql.Driver


# --- Tối ưu kết nối (Tránh lỗi Max connection) ---
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# --- Hibernate Dev ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- SUPABASE & JWT (Phần bị thiếu) ---
# URL & Key để gọi API Supabase
supabase.url=${SUPABASE_URL:https://hmsbwtukwbywmyvcqtby.supabase.co}
supabase.key=${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtc2J3dHVrd2J5d215dmNxdGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5NDgxOTksImV4cCI6MjA4MTUyNDE5OX0.af4uQ1OiNg98uz5UxTNDho9_aSFhNf8LFiwtRbl3P10}

# JWT Secret để giải mã Token (QUAN TRỌNG: Key này phải khớp với key trong file JwtService.java)
jwt.secret=${SUPABASE_JWT_SECRET:semi6pkLDE1X93p1vnY8BOZRofSBXT6rHOgKK2qJSc0kOPiO5NrUt26OXe9CXsGhos/TsAyhMa9+ul6uz2WIUA==}

