# --- SERVER CONFIG ---
server.port=8080

# --- DATABASE CONFIG (SUPABASE) ---
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.twvifiysbagdcllxxzyz
spring.datasource.password=Slibdoancuoiki

spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE CONFIG ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- EMAIL SENDER CONFIG ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hungtestpj01@gmail.com
spring.mail.password=gewl rrvh qasg jqfp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
